In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

df_games = pd.read_parquet('/content/games.parquet')
df_appereances = pd.read_parquet("/content/appearances.parquet")
merged_filtred = pd.read_parquet('/content/merge_filtred_default.parquet')

In [4]:
df_games

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,stadium
105,2368466,CL,2013,group h,2013-11-26,371,5,0,3,null,null,Neil Lennon,Massimiliano Allegri,celtic park,58619.0,Cneyt Cakir,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-2-1,celtic fc,AC Milan,0:3,international_cup,celtic park
106,2368481,CL,2013,group c,2013-12-10,683,58,3,1,null,null,Michel,John van den Brom,stadio georgios karaiskakis,31444.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-1-1,4-1-4-1,olympiacos piraeus,RSC Anderlecht,3:1,international_cup,stadio georgios karaiskakis
111,2384520,CL,2013,group b,2013-12-11,141,506,1,0,null,null,Roberto Mancini,Antonio Conte,ali sami yen spor kompleksi rams park,37375.0,Pedro Proena,https://www.transfermarkt.co.uk/spielbericht/i...,3-5-2,3-5-2 flat,galatasaray,Juventus FC,1:0,international_cup,ali sami yen spor kompleksi rams park
212,2490853,CL,2014,group f,2014-09-17,610,583,1,1,null,null,Frank de Boer,Laurent Blanc,johan cruijff arena,50430.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,4-3-3 Attacking,ajax amsterdam,Paris Saint-Germain,1:1,international_cup,johan cruijff arena
222,2495311,CL,2014,group e,2014-10-21,12,27,1,7,null,null,Rudi Garcia,Pep Guardiola,olimpico di roma,62292.0,Jonas Eriksson,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,3-5-2,as roma,Bayern Munich,1:7,international_cup,olimpico di roma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68274,3651124,CL,2021,group d,2021-11-24,2481,418,0,3,null,null,Yuriy Vernydub,Carlo Ancelotti,sheriff,5932.0,Szymon Marciniak,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-3 Attacking,None,Real Madrid,0:3,international_cup,sheriff
68294,4243700,CL,2023,last 16 2nd leg,2024-03-13,16,383,2,0,null,null,Edin Terzic,Peter Bosz,signal iduna park,81365.0,Daniele Orsato,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-3 Defending,borussia dortmund,PSV Eindhoven,2:0,international_cup,signal iduna park
68304,3651114,CL,2021,group g,2021-11-23,1082,409,1,0,null,null,Jocelyn Gourvennec,Matthias Jaissle,decathlon arena-stade pierre-mauroy,33573.0,Anthony Taylor,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-2 double 6,4-3-1-2,losc lille,None,1:0,international_cup,decathlon arena-stade pierre-mauroy
68312,3098025,CL,2018,group h,2018-11-07,1049,452,3,1,null,null,Marcelino,Gerardo Seoane,mestalla,36480.0,Istvan Kovacs,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-2 double 6,4-4-2 double 6,valencia cf,None,3:1,international_cup,mestalla
68361,2917405,CL,2017,group a,2017-10-31,26,2410,1,2,null,null,Raphael Wicky,Viktor Goncharenko,st. jakob-park,33303.0,Milorad Mazic,https://www.transfermarkt.co.uk/spielbericht/i...,3-4-3,3-4-2-1,None,CSKA Moscow,1:2,international_cup,st. jakob-park

In [5]:
game_stats = df_appereances.groupby(['game_id', 'player_club_id'])[['yellow_cards', 'red_cards', 'goals', 'assists']].sum().reset_index()
game_stats.rename(columns={'player_club_id': 'club_id'}, inplace=True)
game_stats

      game_id  club_id  yellow_cards  red_cards  goals  assists
0     2262147      419             0          0      0        0
1     2262147      720             0          0      2        2
2     2262148      338             0          0      1        1
3     2262148      583             1          0      4        3
4     2262149       11             1          0      2        2
...       ...      ...           ...        ...    ...      ...
2875  4331177      418             1          0      2        1
2876  4331178       27             2          0      2        2
2877  4331178      418             2          0      2        2
2878  4343512       16             3          0      0        0
2879  4343512      418             1          0      2        2

[2880 rows x 6 columns]

In [6]:
df_games
df_games = df_games[['game_id', 'home_club_id', 'away_club_id', 'home_club_name', 'away_club_name', 'home_club_goals', 'away_club_goals', 'home_club_formation', 'away_club_formation']]

In [7]:
df_games

,game_id,home_club_id,away_club_id,home_club_name,away_club_name,home_club_goals,away_club_goals,home_club_formation,away_club_formation
105,2368466,371,5,celtic fc,AC Milan,0,3,4-2-3-1,4-3-2-1
106,2368481,683,58,olympiacos piraeus,RSC Anderlecht,3,1,4-4-1-1,4-1-4-1
111,2384520,141,506,galatasaray,Juventus FC,1,0,3-5-2,3-5-2 flat
212,2490853,610,583,ajax amsterdam,Paris Saint-Germain,1,1,4-3-3 Attacking,4-3-3 Attacking
222,2495311,12,27,as roma,Bayern Munich,1,7,4-3-3 Attacking,3-5-2
...,...,...,...,...,...,...,...,...,...
68274,3651124,2481,418,None,Real Madrid,0,3,4-2-3-1,4-3-3 Attacking
68294,4243700,16,383,borussia dortmund,PSV Eindhoven,2,0,4-2-3-1,4-3-3 Defending
68304,3651114,1082,409,losc lille,None,1,0,4-4-2 double 6,4-3-1-2
68312,3098025,1049,452,valencia cf,None,3,1,4-4-2 double 6,4-4-2 double 6
68361,2917405,26,2410,None,CSKA Moscow,1,2,3-4-3,3-4-2-1

In [17]:
df_games['away_club_name'] = df_games['away_club_name'].str.lower()
df_games['home_club_name'] = df_games['home_club_name'].str.lower()
df_games['home_club_formation'] = df_games['home_club_formation'].str.lower()
df_games['away_club_formation'] = df_games['away_club_formation'].str.lower()
df_games

,game_id,home_club_id,away_club_id,home_club_name,away_club_name,home_club_goals,away_club_goals,home_club_formation,away_club_formation
105,2368466,371,5,celtic fc,ac milan,0,3,4-2-3-1,4-3-2-1
106,2368481,683,58,olympiacos piraeus,rsc anderlecht,3,1,4-4-1-1,4-1-4-1
111,2384520,141,506,galatasaray,juventus fc,1,0,3-5-2,3-5-2 flat
212,2490853,610,583,ajax amsterdam,paris saint-germain,1,1,4-3-3 attacking,4-3-3 attacking
222,2495311,12,27,as roma,bayern munich,1,7,4-3-3 attacking,3-5-2
...,...,...,...,...,...,...,...,...,...
68177,3651139,506,496,juventus fc,none,1,0,4-2-3-1,5-3-2
68184,3913740,583,1064,paris saint-germain,none,7,2,4-3-1-2,3-4-1-2
68294,4243700,16,383,borussia dortmund,psv eindhoven,2,0,4-2-3-1,4-3-3 defending
68304,3651114,1082,409,losc lille,none,1,0,4-4-2 double 6,4-3-1-2
68312,3098025,1049,452,valencia cf,none,3,1,4-4-2 double 6,4-4-2 double 6

In [18]:
# Remoção dos times que não possuem nome - Home club
df_games['home_club_name'] = df_games['home_club_name'].replace('None', np.nan)
df_games = df_games[df_games['home_club_name'].notna()]
# Remoção dos times que não possuem nome - Away club
df_games['away_club_name'] = df_games['away_club_name'].replace('None', np.nan)
df_games = df_games[df_games['away_club_name'].notna()]
df_games

,game_id,home_club_id,away_club_id,home_club_name,away_club_name,home_club_goals,away_club_goals,home_club_formation,away_club_formation
105,2368466,371,5,celtic fc,ac milan,0,3,4-2-3-1,4-3-2-1
106,2368481,683,58,olympiacos piraeus,rsc anderlecht,3,1,4-4-1-1,4-1-4-1
111,2384520,141,506,galatasaray,juventus fc,1,0,3-5-2,3-5-2 flat
212,2490853,610,583,ajax amsterdam,paris saint-germain,1,1,4-3-3 attacking,4-3-3 attacking
222,2495311,12,27,as roma,bayern munich,1,7,4-3-3 attacking,3-5-2
...,...,...,...,...,...,...,...,...,...
68177,3651139,506,496,juventus fc,none,1,0,4-2-3-1,5-3-2
68184,3913740,583,1064,paris saint-germain,none,7,2,4-3-1-2,3-4-1-2
68294,4243700,16,383,borussia dortmund,psv eindhoven,2,0,4-2-3-1,4-3-3 defending
68304,3651114,1082,409,losc lille,none,1,0,4-4-2 double 6,4-3-1-2
68312,3098025,1049,452,valencia cf,none,3,1,4-4-2 double 6,4-4-2 double 6

# Junção dos datasets
Aqui realizamos a junção dos dataset que jugamos relevantes para a analise

Criou uma linha para cada time que em cada uma das partidas de modo que fique correta a disposição dos dados

In [20]:
#Cria um DataFrame para os times da casa
home_teams = df_games[['game_id', 'home_club_id', 'home_club_name', 'home_club_goals', 'home_club_formation', 'away_club_goals']].copy()
home_teams['team_type'] = 'home'
home_teams = home_teams.rename(columns={
    'home_club_id': 'club_id',
    'home_club_name': 'club_name',
    'home_club_goals': 'club_goals',
    'home_club_formation': 'club_formation',
    'away_club_goals': 'suffered_goals'
})

#Cria um DataFrame para os times visitantes
away_teams = df_games[['game_id', 'away_club_id', 'away_club_name', 'away_club_goals', 'away_club_formation', 'home_club_goals']].copy()
away_teams['team_type'] = 'away'
away_teams = away_teams.rename(columns={
    'away_club_id': 'club_id',
    'away_club_name': 'club_name',
    'away_club_goals': 'club_goals',
    'away_club_formation': 'club_formation',
    'home_club_goals': 'suffered_goals'
})

#Transforma os valores de gols sofridos em negativos
home_teams['suffered_goals'] = -home_teams['suffered_goals']
away_teams['suffered_goals'] = -away_teams['suffered_goals']

#Concatena os DataFrames
games_sep_times = pd.concat([home_teams, away_teams])

#Ordena pelo 'game_id'
games_sep_times = games_sep_times.sort_values('game_id')
games_sep_times

,game_id,club_id,club_name,club_goals,club_formation,suffered_goals,team_type
9334,2262148,338,dynamo kyiv,1,none,-4,away
9334,2262148,583,paris saint-germain,4,none,-1,home
20749,2262149,969,montpellier hsc,1,none,-2,home
20749,2262149,11,arsenal fc,2,none,-1,away
59106,2262150,33,fc schalke 04,2,none,-1,away
...,...,...,...,...,...,...,...
20026,4331177,418,real madrid,2,4-3-1-2,-1,home
8513,4331178,27,bayern munich,2,4-2-3-1,-2,home
8513,4331178,418,real madrid,2,4-4-2 double 6,-2,away
51994,4343512,418,real madrid,2,4-3-1-2,0,away
51994,4343512,16,borussia dortmund,0,4-3-3 attacking,-2,home

In [22]:
games_sep_times['club_formation'] = games_sep_times['club_formation'].replace('none', np.nan)
games_sep_times = games_sep_times[games_sep_times['club_formation'].notna()]
games_sep_times

,game_id,club_id,club_name,club_goals,club_formation,suffered_goals,team_type
66271,2367027,15,bayer 04 leverkusen,2,4-3-3 attacking,-4,away
66271,2367027,985,manchester united,4,4-4-1-1,-2,home
37051,2367028,660,shakhtar donetsk,2,4-2-3-1,0,away
37051,2367028,681,real sociedad,0,4-3-3 attacking,-2,home
48243,2367029,418,real madrid,6,4-2-3-1,-1,away
...,...,...,...,...,...,...,...
20026,4331177,418,real madrid,2,4-3-1-2,-1,home
8513,4331178,27,bayern munich,2,4-2-3-1,-2,home
8513,4331178,418,real madrid,2,4-4-2 double 6,-2,away
51994,4343512,418,real madrid,2,4-3-1-2,0,away
51994,4343512,16,borussia dortmund,0,4-3-3 attacking,-2,home

In [23]:
games_sep_times['club_formation'].value_counts()

club_formation
4-2-3-1            703
4-3-3 attacking    666
4-4-2 double 6     241
4-1-4-1            140
3-5-2 flat         131
3-4-2-1            112
4-4-2               74
4-3-1-2             72
4-3-3 defending     57
3-4-3               48
5-4-1               44
5-3-2               32
3-4-1-2             32
4-4-1-1             30
3-5-2               26
4-4-2 diamond       14
4-1-3-2             11
3-5-2 attacking     11
4-5-1 flat           8
4-3-2-1              8
3-1-4-2              7
3-4-3 diamond        3
3-3-3-1              2
4-5-1                2
Name: count, dtype: int64

In [24]:
games_sep_times

,game_id,club_id,club_name,club_goals,club_formation,suffered_goals,team_type
66271,2367027,15,bayer 04 leverkusen,2,4-3-3 attacking,-4,away
66271,2367027,985,manchester united,4,4-4-1-1,-2,home
37051,2367028,660,shakhtar donetsk,2,4-2-3-1,0,away
37051,2367028,681,real sociedad,0,4-3-3 attacking,-2,home
48243,2367029,418,real madrid,6,4-2-3-1,-1,away
...,...,...,...,...,...,...,...
20026,4331177,418,real madrid,2,4-3-1-2,-1,home
8513,4331178,27,bayern munich,2,4-2-3-1,-2,home
8513,4331178,418,real madrid,2,4-4-2 double 6,-2,away
51994,4343512,418,real madrid,2,4-3-1-2,0,away
51994,4343512,16,borussia dortmund,0,4-3-3 attacking,-2,home

In [25]:
game_stats

      game_id  club_id  yellow_cards  red_cards  goals  assists
0     2262147      419             0          0      0        0
1     2262147      720             0          0      2        2
2     2262148      338             0          0      1        1
3     2262148      583             1          0      4        3
4     2262149       11             1          0      2        2
...       ...      ...           ...        ...    ...      ...
2875  4331177      418             1          0      2        1
2876  4331178       27             2          0      2        2
2877  4331178      418             2          0      2        2
2878  4343512       16             3          0      0        0
2879  4343512      418             1          0      2        2

[2880 rows x 6 columns]

In [26]:
merge_game_sep_stats = games_sep_times.merge(game_stats, on=['club_id', 'game_id'])
merge_game_sep_stats_filtred = merge_game_sep_stats[['club_id', 'game_id','club_name', 'club_formation', 'team_type', 'yellow_cards', 'red_cards', 'goals','suffered_goals', 'assists']]

In [41]:
# prompt: merge_game_sep_stats_filtred['is_win'] = 1 if int(merge_game_sep_stats_filtred['goals']) + int(merge_game_sep_stats_filtred['suffered_goals']) > 0 else -1 if int(merge_game_sep_stats_filtred['goals']) + int(merge_game_sep_stats_filtred['suffered_goals']) < 0 else 0
# merge_game_sep_stats_filtred
# ajusta isso para que a regra funcione

def win_condition(row):
  if int(row['goals']) + int(row['suffered_goals']) > 0:
    return 1
  elif int(row['goals']) + int(row['suffered_goals']) < 0:
    return -1
  else:
    return 0

merge_game_sep_stats_filtred['is_win'] = merge_game_sep_stats_filtred.apply(win_condition, axis=1)
merge_game_sep_stats_filtred

,club_id,game_id,club_name,club_formation,team_type,yellow_cards,red_cards,goals,suffered_goals,assists,is_win
0,15,2367027,bayer 04 leverkusen,4-3-3 attacking,away,2,0,2,-4,2,-1
1,985,2367027,manchester united,4-4-1-1,home,1,0,4,-2,4,1
2,660,2367028,shakhtar donetsk,4-2-3-1,away,5,0,2,0,2,1
3,681,2367028,real sociedad,4-3-3 attacking,home,2,0,0,-2,0,-1
4,418,2367029,real madrid,4-2-3-1,away,1,0,6,-1,6,1
...,...,...,...,...,...,...,...,...,...,...,...
2419,418,4331177,real madrid,4-3-1-2,home,1,0,2,-1,1,1
2420,27,4331178,bayern munich,4-2-3-1,home,2,0,2,-2,2,0
2421,418,4331178,real madrid,4-4-2 double 6,away,2,0,2,-2,2,0
2422,418,4343512,real madrid,4-3-1-2,away,1,0,2,0,2,1
2423,16,4343512,borussia dortmund,4-3-3 attacking,home,3,0,0,-2,0,-1

In [42]:
merge_game_sep_stats_filtred

,club_id,game_id,club_name,club_formation,team_type,yellow_cards,red_cards,goals,suffered_goals,assists,is_win
0,15,2367027,bayer 04 leverkusen,4-3-3 attacking,away,2,0,2,-4,2,-1
1,985,2367027,manchester united,4-4-1-1,home,1,0,4,-2,4,1
2,660,2367028,shakhtar donetsk,4-2-3-1,away,5,0,2,0,2,1
3,681,2367028,real sociedad,4-3-3 attacking,home,2,0,0,-2,0,-1
4,418,2367029,real madrid,4-2-3-1,away,1,0,6,-1,6,1
...,...,...,...,...,...,...,...,...,...,...,...
2419,418,4331177,real madrid,4-3-1-2,home,1,0,2,-1,1,1
2420,27,4331178,bayern munich,4-2-3-1,home,2,0,2,-2,2,0
2421,418,4331178,real madrid,4-4-2 double 6,away,2,0,2,-2,2,0
2422,418,4343512,real madrid,4-3-1-2,away,1,0,2,0,2,1
2423,16,4343512,borussia dortmund,4-3-3 attacking,home,3,0,0,-2,0,-1

In [44]:
stats = merge_game_sep_stats_filtred[['yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists', 'is_win']]

cols_to_dummy = merge_game_sep_stats_filtred.drop(columns=['club_id', 'game_id', 'yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists', 'is_win'])

cols_dummified = pd.get_dummies(cols_to_dummy)
cols_dummified = cols_dummified.astype(int)

merge_game_sep_stats_filtred_dummy = pd.concat([stats, cols_dummified], axis=1)
merge_game_sep_stats_filtred_dummy

,yellow_cards,red_cards,goals,suffered_goals,assists,is_win,club_name_1.fc union berlin,club_name_ac milan,club_name_aek athens,club_name_ajax amsterdam,club_name_arsenal fc,club_name_as monaco,club_name_as roma,club_name_atalanta bc,club_name_athletic bilbao,club_name_atltico de madrid,club_name_basaksehir fk,club_name_bayer 04 leverkusen,club_name_bayern munich,club_name_besiktas jk,club_name_borussia dortmund,club_name_borussia mnchengladbach,club_name_celtic fc,club_name_chelsea fc,club_name_club brugge kv,club_name_cska moscow,club_name_dynamo kyiv,club_name_eintracht frankfurt,club_name_fc barcelona,club_name_fc copenhagen,club_name_fc midtjylland,club_name_fc porto,club_name_fc schalke 04,club_name_feyenoord rotterdam,club_name_fk krasnodar,club_name_fk rostov,club_name_galatasaray,club_name_inter milan,club_name_juventus fc,club_name_kaa gent,club_name_krc genk,club_name_leicester city,club_name_liverpool fc,club_name_lokomotiv moscow,club_name_losc lille,club_name_manchester city,club_name_manchester united,club_name_newcastle united,club_name_none,club_name_olympiacos piraeus,club_name_olympique lyon,club_name_olympique marseille,club_name_paris saint-germain,club_name_psv eindhoven,club_name_rangers fc,club_name_rb leipzig,club_name_rc lens,club_name_real madrid,club_name_real sociedad,club_name_royal antwerp fc,club_name_rsc anderlecht,club_name_sc braga,club_name_sevilla fc,club_name_shakhtar donetsk,club_name_sl benfica,club_name_spartak moscow,club_name_sporting cp,club_name_ss lazio,club_name_ssc napoli,club_name_stade rennais fc,club_name_tottenham hotspur,club_name_tsg 1899 hoffenheim,club_name_valencia cf,club_name_vfl wolfsburg,club_name_villarreal cf,club_name_zenit st. petersburg,club_formation_3-1-4-2,club_formation_3-3-3-1,club_formation_3-4-1-2,club_formation_3-4-2-1,club_formation_3-4-3,club_formation_3-4-3 diamond,club_formation_3-5-2,club_formation_3-5-2 attacking,club_formation_3-5-2 flat,club_formation_4-1-3-2,club_formation_4-1-4-1,club_formation_4-2-3-1,club_formation_4-3-1-2,club_formation_4-3-2-1,club_formation_4-3-3 attacking,club_formation_4-3-3 defending,club_formation_4-4-1-1,club_formation_4-4-2,club_formation_4-4-2 diamond,club_formation_4-4-2 double 6,club_formation_4-5-1,club_formation_4-5-1 flat,club_formation_5-3-2,club_formation_5-4-1,team_type_away,team_type_home
0,2,0,2,-4,2,-1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
1,1,0,4,-2,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2,5,0,2,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,2,0,0,-2,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
4,1,0,6,-1,6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,1,0,2,-1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2420,2,0,2,-2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2421,2,0,2,-2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2422,1,0,2,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
2423,3,0,0,-2,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

In [45]:
from sklearn.preprocessing import MinMaxScaler

# Select the columns to be scaled
columns_to_scale = ['yellow_cards', 'red_cards', 'goals', 'assists']
columns_to_scale_negative = ['suffered_goals']

# Create a MinMaxScaler object
scaler = MinMaxScaler()
scaler_negative = MinMaxScaler(feature_range=(-1, 0))

merge_game_sep_stats_filtred_normalized = merge_game_sep_stats_filtred.copy()

# Apply MinMaxScaler to the selected columns
merge_game_sep_stats_filtred_normalized[columns_to_scale] = scaler.fit_transform(merge_game_sep_stats_filtred[columns_to_scale])
merge_game_sep_stats_filtred_normalized[columns_to_scale_negative] = scaler_negative.fit_transform(merge_game_sep_stats_filtred[columns_to_scale_negative])

# Display the updated DataFrame
merge_game_sep_stats_filtred_normalized

,club_id,game_id,club_name,club_formation,team_type,yellow_cards,red_cards,goals,suffered_goals,assists,is_win
0,15,2367027,bayer 04 leverkusen,4-3-3 attacking,away,0.250,0.0,0.25,-0.500,0.250,-1
1,985,2367027,manchester united,4-4-1-1,home,0.125,0.0,0.50,-0.250,0.500,1
2,660,2367028,shakhtar donetsk,4-2-3-1,away,0.625,0.0,0.25,0.000,0.250,1
3,681,2367028,real sociedad,4-3-3 attacking,home,0.250,0.0,0.00,-0.250,0.000,-1
4,418,2367029,real madrid,4-2-3-1,away,0.125,0.0,0.75,-0.125,0.750,1
...,...,...,...,...,...,...,...,...,...,...,...
2419,418,4331177,real madrid,4-3-1-2,home,0.125,0.0,0.25,-0.125,0.125,1
2420,27,4331178,bayern munich,4-2-3-1,home,0.250,0.0,0.25,-0.250,0.250,0
2421,418,4331178,real madrid,4-4-2 double 6,away,0.250,0.0,0.25,-0.250,0.250,0
2422,418,4343512,real madrid,4-3-1-2,away,0.125,0.0,0.25,0.000,0.250,1
2423,16,4343512,borussia dortmund,4-3-3 attacking,home,0.375,0.0,0.00,-0.250,0.000,-1

In [46]:
stats = merge_game_sep_stats_filtred_normalized[['yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists']]

cols_to_dummy = merge_game_sep_stats_filtred_normalized.drop(columns=['club_id', 'game_id','yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists'])

cols_dummified = pd.get_dummies(cols_to_dummy)
cols_dummified = cols_dummified.astype(int)

merge_game_sep_stats_filtred_normalized_dummy = pd.concat([stats, cols_dummified], axis=1)
merge_game_sep_stats_filtred_normalized_dummy

,yellow_cards,red_cards,goals,suffered_goals,assists,is_win,club_name_1.fc union berlin,club_name_ac milan,club_name_aek athens,club_name_ajax amsterdam,club_name_arsenal fc,club_name_as monaco,club_name_as roma,club_name_atalanta bc,club_name_athletic bilbao,club_name_atltico de madrid,club_name_basaksehir fk,club_name_bayer 04 leverkusen,club_name_bayern munich,club_name_besiktas jk,club_name_borussia dortmund,club_name_borussia mnchengladbach,club_name_celtic fc,club_name_chelsea fc,club_name_club brugge kv,club_name_cska moscow,club_name_dynamo kyiv,club_name_eintracht frankfurt,club_name_fc barcelona,club_name_fc copenhagen,club_name_fc midtjylland,club_name_fc porto,club_name_fc schalke 04,club_name_feyenoord rotterdam,club_name_fk krasnodar,club_name_fk rostov,club_name_galatasaray,club_name_inter milan,club_name_juventus fc,club_name_kaa gent,club_name_krc genk,club_name_leicester city,club_name_liverpool fc,club_name_lokomotiv moscow,club_name_losc lille,club_name_manchester city,club_name_manchester united,club_name_newcastle united,club_name_none,club_name_olympiacos piraeus,club_name_olympique lyon,club_name_olympique marseille,club_name_paris saint-germain,club_name_psv eindhoven,club_name_rangers fc,club_name_rb leipzig,club_name_rc lens,club_name_real madrid,club_name_real sociedad,club_name_royal antwerp fc,club_name_rsc anderlecht,club_name_sc braga,club_name_sevilla fc,club_name_shakhtar donetsk,club_name_sl benfica,club_name_spartak moscow,club_name_sporting cp,club_name_ss lazio,club_name_ssc napoli,club_name_stade rennais fc,club_name_tottenham hotspur,club_name_tsg 1899 hoffenheim,club_name_valencia cf,club_name_vfl wolfsburg,club_name_villarreal cf,club_name_zenit st. petersburg,club_formation_3-1-4-2,club_formation_3-3-3-1,club_formation_3-4-1-2,club_formation_3-4-2-1,club_formation_3-4-3,club_formation_3-4-3 diamond,club_formation_3-5-2,club_formation_3-5-2 attacking,club_formation_3-5-2 flat,club_formation_4-1-3-2,club_formation_4-1-4-1,club_formation_4-2-3-1,club_formation_4-3-1-2,club_formation_4-3-2-1,club_formation_4-3-3 attacking,club_formation_4-3-3 defending,club_formation_4-4-1-1,club_formation_4-4-2,club_formation_4-4-2 diamond,club_formation_4-4-2 double 6,club_formation_4-5-1,club_formation_4-5-1 flat,club_formation_5-3-2,club_formation_5-4-1,team_type_away,team_type_home
0,0.250,0.0,0.25,-0.500,0.250,-1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
1,0.125,0.0,0.50,-0.250,0.500,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2,0.625,0.0,0.25,0.000,0.250,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,0.250,0.0,0.00,-0.250,0.000,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
4,0.125,0.0,0.75,-0.125,0.750,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,0.125,0.0,0.25,-0.125,0.125,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2420,0.250,0.0,0.25,-0.250,0.250,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2421,0.250,0.0,0.25,-0.250,0.250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2422,0.125,0.0,0.25,0.000,0.250,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
2423,0.375,0.0,0.00,-0.250,0.000,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

In [47]:
from sklearn.preprocessing import StandardScaler

# Selecionar as colunas a serem padronizadas
columns_to_standardize = ['yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists']

# Criar um objeto StandardScaler
scaler = StandardScaler()

# Aplicar a padronização nas colunas selecionadas
merge_game_sep_stats_filtred_standardized = merge_game_sep_stats_filtred.copy()
merge_game_sep_stats_filtred_standardized[columns_to_standardize] = scaler.fit_transform(merge_game_sep_stats_filtred[columns_to_standardize])

# Exibir o DataFrame atualizado
merge_game_sep_stats_filtred_standardized

,club_id,game_id,club_name,club_formation,team_type,yellow_cards,red_cards,goals,suffered_goals,assists,is_win
0,15,2367027,bayer 04 leverkusen,4-3-3 attacking,away,0.036799,-0.188349,0.422286,-1.811254,0.664507,-1
1,985,2367027,manchester united,4-4-1-1,home,-0.660087,-0.188349,1.893005,-0.370572,2.291544,1
2,660,2367028,shakhtar donetsk,4-2-3-1,away,2.127459,-0.188349,0.422286,1.070111,0.664507,1
3,681,2367028,real sociedad,4-3-3 attacking,home,0.036799,-0.188349,-1.048433,-0.370572,-0.962529,-1
4,418,2367029,real madrid,4-2-3-1,away,-0.660087,-0.188349,3.363723,0.349770,3.918580,1
...,...,...,...,...,...,...,...,...,...,...,...
2419,418,4331177,real madrid,4-3-1-2,home,-0.660087,-0.188349,0.422286,0.349770,-0.149011,1
2420,27,4331178,bayern munich,4-2-3-1,home,0.036799,-0.188349,0.422286,-0.370572,0.664507,0
2421,418,4331178,real madrid,4-4-2 double 6,away,0.036799,-0.188349,0.422286,-0.370572,0.664507,0
2422,418,4343512,real madrid,4-3-1-2,away,-0.660087,-0.188349,0.422286,1.070111,0.664507,1
2423,16,4343512,borussia dortmund,4-3-3 attacking,home,0.733686,-0.188349,-1.048433,-0.370572,-0.962529,-1

In [50]:
stats = merge_game_sep_stats_filtred_standardized[['yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists']]

cols_to_dummy = merge_game_sep_stats_filtred_standardized.drop(columns=['club_id', 'game_id','yellow_cards', 'red_cards', 'goals', 'suffered_goals', 'assists'])

cols_dummified = pd.get_dummies(cols_to_dummy)
cols_dummified = cols_dummified.astype(int)

merge_game_sep_stats_filtred_standardized_dummy = pd.concat([stats, cols_dummified], axis=1)
merge_game_sep_stats_filtred_standardized_dummy

,yellow_cards,red_cards,goals,suffered_goals,assists,is_win,club_name_1.fc union berlin,club_name_ac milan,club_name_aek athens,club_name_ajax amsterdam,club_name_arsenal fc,club_name_as monaco,club_name_as roma,club_name_atalanta bc,club_name_athletic bilbao,club_name_atltico de madrid,club_name_basaksehir fk,club_name_bayer 04 leverkusen,club_name_bayern munich,club_name_besiktas jk,club_name_borussia dortmund,club_name_borussia mnchengladbach,club_name_celtic fc,club_name_chelsea fc,club_name_club brugge kv,club_name_cska moscow,club_name_dynamo kyiv,club_name_eintracht frankfurt,club_name_fc barcelona,club_name_fc copenhagen,club_name_fc midtjylland,club_name_fc porto,club_name_fc schalke 04,club_name_feyenoord rotterdam,club_name_fk krasnodar,club_name_fk rostov,club_name_galatasaray,club_name_inter milan,club_name_juventus fc,club_name_kaa gent,club_name_krc genk,club_name_leicester city,club_name_liverpool fc,club_name_lokomotiv moscow,club_name_losc lille,club_name_manchester city,club_name_manchester united,club_name_newcastle united,club_name_none,club_name_olympiacos piraeus,club_name_olympique lyon,club_name_olympique marseille,club_name_paris saint-germain,club_name_psv eindhoven,club_name_rangers fc,club_name_rb leipzig,club_name_rc lens,club_name_real madrid,club_name_real sociedad,club_name_royal antwerp fc,club_name_rsc anderlecht,club_name_sc braga,club_name_sevilla fc,club_name_shakhtar donetsk,club_name_sl benfica,club_name_spartak moscow,club_name_sporting cp,club_name_ss lazio,club_name_ssc napoli,club_name_stade rennais fc,club_name_tottenham hotspur,club_name_tsg 1899 hoffenheim,club_name_valencia cf,club_name_vfl wolfsburg,club_name_villarreal cf,club_name_zenit st. petersburg,club_formation_3-1-4-2,club_formation_3-3-3-1,club_formation_3-4-1-2,club_formation_3-4-2-1,club_formation_3-4-3,club_formation_3-4-3 diamond,club_formation_3-5-2,club_formation_3-5-2 attacking,club_formation_3-5-2 flat,club_formation_4-1-3-2,club_formation_4-1-4-1,club_formation_4-2-3-1,club_formation_4-3-1-2,club_formation_4-3-2-1,club_formation_4-3-3 attacking,club_formation_4-3-3 defending,club_formation_4-4-1-1,club_formation_4-4-2,club_formation_4-4-2 diamond,club_formation_4-4-2 double 6,club_formation_4-5-1,club_formation_4-5-1 flat,club_formation_5-3-2,club_formation_5-4-1,team_type_away,team_type_home
0,0.036799,-0.188349,0.422286,-1.811254,0.664507,-1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
1,-0.660087,-0.188349,1.893005,-0.370572,2.291544,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2,2.127459,-0.188349,0.422286,1.070111,0.664507,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,0.036799,-0.188349,-1.048433,-0.370572,-0.962529,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
4,-0.660087,-0.188349,3.363723,0.349770,3.918580,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2419,-0.660087,-0.188349,0.422286,0.349770,-0.149011,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2420,0.036799,-0.188349,0.422286,-0.370572,0.664507,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2421,0.036799,-0.188349,0.422286,-0.370572,0.664507,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2422,-0.660087,-0.188349,0.422286,1.070111,0.664507,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
2423,0.733686,-0.188349,-1.048433,-0.370572,-0.962529,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

# Salvando tabelas na pasta data
1. Merge_Filtred.parquet
2. Merge_Normalized_Dummy.parquet
3. Merge_Standardized_Dummy.parquet

In [51]:
merge_game_sep_stats_filtred.to_parquet("/content/clustering/data/merge_filtred_default.parquet")
merge_game_sep_stats_filtred_dummy.to_parquet("/content/clustering/data/merge_filtred_default_dummy.parquet")
merge_game_sep_stats_filtred_normalized_dummy.to_parquet("/content/clustering/data/merge_normalized_dummy.parquet")
merge_game_sep_stats_filtred_standardized_dummy.to_parquet("/content/clustering/data/merge_standardized_dummy.parquet")